apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.stack_name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.label }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
      - name: wordpress
        image: {{ .Values.image }}:{{ .Values.image_tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            name: http
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
        - name: WORDPRESS_DB_USER
          value: "{{ .Values.wp_db.user }}"
        - name: WORDPRESS_DB_HOST
          value: "{{ .Values.wp_db.host }}"
        - name: WORDPRESS_DB_NAME
          value: "{{ .Values.wp_db.name }}"
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
