apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.stack_name }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: {{ .Values.wp_disk_capacity }}Gi
