---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.stack_name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.label }}
spec:
  clusterIP: None
  ports:
  - port: 80
    name: http
  selector:
    app: {{ .Values.label }}
