apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  selector:
    matchLabels:
      app: wp-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: wp-frontend
    spec:
      containers:
      - name: wordpress
        image: wordpress:5.2.2-php7.1-apache
        imagePullPolicy: Always
        ports:
          - containerPort: 80
            name: http
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
        - name: WORDPRESS_DB_USER
          value: "admin"
        - name: WORDPRESS_DB_HOST
          value: "<WP_DB_HOST>"
        - name: WORDPRESS_DB_NAME
          value: "sgtask"
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define('WP_HOME', 'http://<ALB_DNS>');
            define('WP_SITEURL', 'http://<ALB_DNS>'); 
        readinessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
